# Generated by Django 3.0.5 on 2023-07-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishname', models.CharField(max_length=300)),
                ('hindiname', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishname', models.CharField(max_length=300)),
                ('hindiname', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('categoryid', models.PositiveIntegerField(null=True)),
                ('categoryname', models.CharField(max_length=200, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('customername', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.Category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.Product')),
            ],
        ),
    ]
